<?php
$shouldSync=$this->localhostSynced();

if($shouldSync){
    ?>
    <div id="autosuggest-notification" class="notification-global">
        <a target="_blank" href="<?php echo $block->getUrl('adminhtml/autocompleteplus_push/startpush');?>">
            <b><?php echo  __('Sync now'); ?></b>
        </a>
        <?php echo __(' to complete the initial <strong>InstantSearch+</strong> product synchronization with our cloud service') ?>.
    </div>
<?php
}
?>