<?php
$shouldSync = $this->localhostSynced();

if ($shouldSync) {
    ?>
    <div id="autosuggest-notification" class="notification-global">
        <a target="_blank" href="<?= /* @noEscape */ $block->getUrl('adminhtml/autocompleteplus_push/startpush');?>">
            <b><?= /* @noEscape */ __('Sync now'); ?></b>
        </a>
        <?= /* @noEscape */ __(' to complete the initial <strong>InstantSearch+</strong> product synchronization with our cloud service') ?>.
    </div>
    <?php
}
?>