<script>
    <?php if ($block->getis_serp() == '0') : ?>
        var lp_slug = "<?php if ($block->getData('slug')) { /* @noEscape */echo $block->getData('slug'); } ?>";
    <?php endif; ?>
    var __isp_fulltext_search_obj = {
        uuid: "<?= /* @noEscape */ $block->getApiUUID();?>",
        store_id: <?= /* @noEscape */ $block->getStoreId();?>
    };
</script>
<?php $results = $block->getSearchResults(); ?>
<?= /* @noEscape */ $results; ?>